spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/permission_fast?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    #配置 https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          #login-username: admin
          #login-password: admin
      filter:
          #配置详情:https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
          stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: false
          #配置详情:https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE-wallfilter
          wall:
              config:
                  multi-statement-allow: true




